name: merhaba_app
description: "A social media app series Coder YT Channel"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.8.1
  flutter_secure_storage: ^9.2.2
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  fluttertoast: ^8.2.10
  fluent_ui: ^4.9.2
  persistent_bottom_nav_bar: ^6.2.1
  cached_network_image: ^3.4.1
  path: ^1.9.0
  adaptive_theme: ^3.6.0
  flutter_localization: ^0.3.1
  carousel_slider: ^5.0.0
  flick_video_player: ^0.9.0
  flutter_osm_plugin: ^1.3.6
  flutter_animate: ^4.5.2
  swipe_refresh: ^1.1.2
  flutter_reaction_button: ^3.0.0+3
  timeago: ^3.7.0
  photo_view: ^0.15.0
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
    - assets/fonts/

  fonts:
    - family: KingsguardCalligraphy
      fonts:
        - asset: assets/fonts/KingsguardCalligraphy.otf
          weight: 700
